WINDOW_WIDTH = 1110
WINDOW_HEIGHT = 668
"""
# ascii values
RIGHT_ARROW = 1073741903
LEFT_ARROW = 1073741904
DOWN_ARROW = 1073741905
UP_ARROW = 1073741906
"""
SPEED = 4
BOOSTERS_SPEED = 6
ENEMY_SIZE = 50
# BLUE_ENEMY_LOCATION = 'Images/blue_enemy.png'
SPACE_BETWEEN_BACKGROUND_OBJECTS_X = 350
SPACE_BETWEEN_MOVING_OBJECTS_X = 500
SPACE_BETWEEN_MOVING_OBJECTS_Y = 70
TOP_Y_YOS = 480
GROUND_OBSTACLE_IMAGES = ['images/blue_enemy.png', 'images/brown_enemy.png', 'images/red_enemy.png']
BOOSTER_IMAGES = ['images/golden_mushroom.png', 'images/red_mushroom.png', 'images/blue_mushroom.png']
BOOSTER_POINTS = [10, 7, 5]
BOOSTERS_SIZE = 50
SKY_OBSTACLE_IMAGES = ['images/blue_bird.png', 'images/red_bird.png']
SKY_BACKGROUND_OBJECTS_IMAGES = ['images/big_cloud.png', 'images/small_cloud.png']
SKY_BACKGROUND_WIDTH = [214, 130]
SKY_BACKGROUND_HEIGHT = [107, 106]
BACKGROUND_OBJECTS_SPEED = 3
TOP_Y_YOS_FOR_BACKGROUND_OBJECTS = 100

# Super Mario
SUPER_MARIO_START_X_POS = 50
SUPER_MARIO_START_Y_POS = 520
SUPER_MARIO_HEIGHT = 81 # 54
SUPER_MARIO_WIDTH = 69 # 46
SUPER_MARIO_IMG_PATH = 'images/super_mario.png'
SUPER_MARIO_JUMP_IMG_PATH = 'images/mario_jumps.png'
SUPER_MARIO_BEND_IMG_PATH = 'images/mario_bends.png'
MINI_MOVE_IN_Y = 5
JUMP_SPEED = 6
BEND_SPEED = 2
BEND_HEIGHT_CHANGE = 2
BEND_WIDTH_CHANGE = 1
LIMIT_FOR_JUMP = 380
LIMIT_FOR_BEND = 40
X_MOVE_DISTANCE_IN_JUMP_AND_BEND = 2

# Colors
BLACK = (0, 0, 0)

# Points
POINTS_TEXT_SIZE = 30
POINTS_TEXT_X = 10
POINTS_TEXT_Y = 10
TICKS_BEFORE_POINT_IS_ADDED = 20
